# Generated by Django 5.0 on 2026-02-10 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Query",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_input", models.TextField()),
                (
                    "detected_language",
                    models.CharField(
                        choices=[
                            ("tamil", "Tamil"),
                            ("english", "English"),
                            ("tanglish", "Tanglish"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "detected_intent",
                    models.CharField(
                        choices=[
                            ("creative_writing", "Creative Writing"),
                            ("coding", "Coding"),
                            ("business", "Business"),
                            ("analysis", "Analysis"),
                            ("email_professional", "Email/Professional"),
                            ("learning", "Learning"),
                            ("conversational", "Conversational"),
                        ],
                        default="conversational",
                        max_length=100,
                    ),
                ),
                ("enhanced_prompt", models.TextField()),
                ("selected_model", models.CharField(max_length=50)),
                ("ai_response", models.TextField(blank=True, null=True)),
                (
                    "user_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Query",
                "verbose_name_plural": "User Queries",
                "ordering": ["-created_at"],
            },
        ),
    ]
