# Generated by Django 6.0.2 on 2026-02-12 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (5, "⭐⭐⭐⭐⭐ Excellent"),
                            (4, "⭐⭐⭐⭐ Very Good"),
                            (3, "⭐⭐⭐ Good"),
                            (2, "⭐⭐ Fair"),
                            (1, "⭐ Poor"),
                        ]
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_positive", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Feedback",
                "verbose_name_plural": "Customer Feedbacks",
                "ordering": ["-created_at"],
            },
        ),
    ]
